Feat/favorite button
angelavbalves/PopMovies pull request #10
Opened 2022-11-10 20:47 UTC by angelavbalves

### ℹ️ Descrição
     Construção do botão para marcar filmes como favoritos
 ### 🎨 Mudanças
- Altera o icon dos filmes favoritos na tab bar
- Constrói a view model, controller, view e a própria célula para exibir a listagem de filmes favoritos
- Constrói um componente do botão para realizar a animação quando clicado
- Controla se o filme está marcado como favorito em uma nova variável criada na model e salvo no CoreData
- Configura o botão de favorito na tela de detalhes

2022-12-03 00:07 UTC, carlosbarceloss commented on PopMovies/PopMovies/Sources/Common/Components/PMButton.swift
> +        self.setTitle("Add to favorites", for: .normal)
Tendo em vista que vc criou um botão pra ser meio "genérico" - `PMButton`, não seria o ideal marretar o título dele dentro dessa função, porquê pode causar um comportamento inesperado caso em algum momento você busque utilizar ele para outra função.

Sugiro:
a) Alterar o nome da classe para `FavoriteButton`, deixando claro o que é o componente
b) Não colocar o título aqui, e aí deixar essa responsabilidade para quem instanciar o componente.

2022-12-03 00:20 UTC, carlosbarceloss requested changes

2022-12-03 00:20 UTC, carlosbarceloss commented on PopMovies/PopMovies/Sources/Views/FavoriteMovies/Views/FavoritesMovieViewController.swift
> +    private lazy var tableView = FavoriteMoviesView(removeFavoriteMovie: removeFavoriteMovie(for:))
```suggestion
    private lazy var rootView = FavoriteMoviesView(removeFavoriteMovie: removeFavoriteMovie(for:))
```

2022-12-03 00:20 UTC, carlosbarceloss commented on PopMovies/PopMovies/Sources/Views/FavoriteMovies/Views/FavoritesMovieViewController.swift
> +        viewModel.fetchFavoritesMovies()
Acho que isso tudo podia estar dentro da mesma função, algo tipo:
```swift
func fetchFavoriteMoviesAndUpdateView() { 
    let favoriteMovies = viewModel.fetchFavoriteMovies
    rootView.receive(favoriteMovies)
}
```

2022-12-03 00:20 UTC, carlosbarceloss commented on PopMovies/PopMovies/Sources/Views/FavoriteMovies/Views/FavoriteMoviesView.swift
> +    func popularFavoriteMoviesList(with favoriteMovies: [MovieItem]) {
```suggestion
    func receive(_ favoriteMovies: [MovieItem]) {
```

2022-12-03 00:20 UTC, carlosbarceloss commented on PopMovies/PopMovies/Sources/Views/FavoriteMovies/Views/FavoritesMovieViewController.swift
> +    func removeFavoriteMovie(for id: Int) {
```suggestion
    func removeFavoriteMovie(with id: Int) {
```

2022-12-03 00:20 UTC, carlosbarceloss commented on PopMovies/PopMovies/Sources/Views/FavoriteMovies/ViewModel/FavoriteMoviesViewModel.swift
> +    func removeFavoriteMovie(for id: Int) {
```suggestion
    func removeFavoriteMovie(with id: Int) {
```

2022-12-03 00:20 UTC, carlosbarceloss commented on PopMovies/PopMovies/Sources/Views/MovieDetails/Views/MovieDetailsView.swift
> +    var favoriteButtonUnselectedAction: (_ id: Int) -> Void
```suggestion
    let favoriteButtonSelectedAction: (_ movie: MovieItem) -> Void
    let favoriteButtonUnselectedAction: (_ id: Int) -> Void
```

além disso, acredito que poderia fazer isso através de uma única função, apenas passando o `movie` pra sua `viewModel`:

```swift
// FavoriteMoviesViewModel
func didTapFavoriteButton(for movie: MovieItem) { 
    // Verifica se o movie está nos favoritos, caso estiver, remove, se não, adiciona
    if isFavoriteMovie { 
        removeMovie()
    } else { 
        addMovie() 
    }
}
```

2022-12-03 00:20 UTC, carlosbarceloss commented on PopMovies/PopMovies/Sources/Views/MovieDetails/Views/MovieDetailsViewController.swift
> +        favoriteButtonUnselectedAction: buttonUnselected(_:)
usar `weak self` para evitar memory leaks

2022-12-05 13:12 UTC, angelavbalves commented on PopMovies/PopMovies/Sources/Common/Components/PMButton.swift
> +        self.setTitle("Add to favorites", for: .normal)
Tendo em vista que o único botão que necessito é o de adicionar aos favoritos, optei por alterar o nome da classe para FavoriteButton

2022-12-05 13:25 UTC, angelavbalves commented on PopMovies/PopMovies/Sources/Views/FavoriteMovies/Views/FavoritesMovieViewController.swift
> +    private lazy var tableView = FavoriteMoviesView(removeFavoriteMovie: removeFavoriteMovie(for:))
Realizei essa alteração em uma nova branch ( #24 ) e também inclui o [ weak self ]  para evitar retain cycles

2022-12-05 13:39 UTC, angelavbalves commented on PopMovies/PopMovies/Sources/Views/FavoriteMovies/Views/FavoriteMoviesView.swift
> +    func popularFavoriteMoviesList(with favoriteMovies: [MovieItem]) {
Alterei o nome dessa função na branch mais recente

2022-12-05 13:40 UTC, angelavbalves commented on PopMovies/PopMovies/Sources/Views/FavoriteMovies/ViewModel/FavoriteMoviesViewModel.swift
> +    func removeFavoriteMovie(for id: Int) {
Fiz essa alteração na nova branch com as demais mudanças sugeridas

2022-12-05 13:46 UTC, angelavbalves commented on PopMovies/PopMovies/Sources/Views/MovieDetails/Views/MovieDetailsViewController.swift
> +        favoriteButtonUnselectedAction: buttonUnselected(_:)
Já inseri o weak self na nova branch em que realizo as mudanças sugeridas

2022-12-23 19:37 UTC, merged