Feat/service
angelavbalves/PopMovies pull request #2
Opened 2022-10-25 19:44 UTC by angelavbalves

### ℹ️  Descrição
     Implementação da camada de service

### 🎨 Mudanças
- Realiza a requisição com uma função genérica
- Constrói a url da API a ser consumida por meio de endpoints
- Realiza os testes com um fake json e um ClientMock

2022-11-11 00:29 UTC, carlosbarceloss requested changes

2022-11-11 00:29 UTC, carlosbarceloss commented on PopMovies/PopMovies/Sources/Service/PMService.swift
> +        )
Aqui eu acho que daria pra melhorar um pouco a formatação, o que você acha?
```swift
        .init(
            getMovies: { page, result in
                apiClient.makeRequest(
                    endpoint: .movies(page: page),
                    result
                )
            },
            similarMovies: { id, page, result in
                apiClient.makeRequest(
                    endpoint: .similarMovies(
                        id: id,
                        page: page
                    ),
                    result
                )
            },
            searchMovies: { page, query, result in
                apiClient.makeRequest(
                    endpoint: .searchMovies(
                        page: page,
                        query: query
                    ),
                    result
                )
            }
        )
```

A ideia é, basicamente, ir quebrando linhas entre os parâmetros, e os fechamentos de parênteses/chaves também numa linha separada (quando fizer sentido). Acredito que melhora bastante a legibilidade.

2022-11-11 00:29 UTC, carlosbarceloss commented on PopMovies/PopMovies/Sources/Service/PopMoviesClient.swift
> +                guard let data = data else { return }
Nesse caso aqui, quando você por algum motivo não recebe o objeto `Data`, acho que é bacana lançar um `completion(.failure()`, tipo:
```swift
guard let data = data else {
    completion(.failure(.generic("Unexpected failure, unable to recover data from the server.")))
    return
}
```

2022-11-11 00:29 UTC, carlosbarceloss commented on PopMovies/PopMoviesTests/Service/PMServiceTests.swift
> +    }
Vale dar uma formatada nesse arquivo tbm, a função de teste do `similarMoviesEndpoint` e `searchMoviesEndpoint` estão bem fora do padrão

2022-11-11 00:29 UTC, carlosbarceloss commented on PopMovies/PopMoviesTests/Service/PMServiceTests.swift
> +    func test_withSearchMoviesEnpoint() {
Aqui poderia ser tipo...
```suggestion
    func test_searchMovies_shouldBuildExpectedEndpoint() {
```
pra ser mais declarativo, o que vc acha?

A mesma sugestão serve para as demais funções.

2022-11-11 00:29 UTC, carlosbarceloss commented on PopMovies/PopMoviesTests/ValidateDecoderJSON/ValidadeDecodeJSON.swift
> +class ValidadeDecoderJSON: XCTestCase {
Acho que rolou um typo aqui:
```suggestion
class ValidateDecoderJSON: XCTestCase {
```

Anyways, sugiro o nome `ValidateDataJSONDecoder`

2022-11-11 00:29 UTC, carlosbarceloss commented on PopMovies/PopMoviesTests/ValidateDecoderJSON/ValidadeDecodeJSON.swift
> +        validJSON = try! Data(contentsOf: validRUL)
typo
```suggestion
        validJSON = try! Data(contentsOf: validURL)
```

2022-11-11 00:29 UTC, carlosbarceloss commented on PopMovies/PopMoviesTests/ValidateDecoderJSON/ValidadeDecodeJSON.swift
> +
extra line
```suggestion
```

2022-11-11 00:29 UTC, carlosbarceloss commented on PopMovies/PopMoviesTests/ValidateDecoderJSON/ValidadeDecodeJSON.swift
> +
extra line
```suggestion
```

2022-11-21 15:36 UTC, angelavbalves commented on PopMovies/PopMovies/Sources/Service/PMService.swift
> +        )
- Realizei as mudanças sugeridas em uma nova branch #15  que já está aberta em um novo PR para você conferir

2022-12-02 23:44 UTC, carlosbarceloss approved these changes

2022-12-05 12:16 UTC, merged