Feat/view controllers
angelavbalves/PopMovies pull request #4
Opened 2022-10-25 19:59 UTC by angelavbalves

### ℹ️ Descrição
    Criação das ViewControllers

### 🎨 Mudanças
- Cria as controllers de listagem de filmes populares, favoritos e por gênero
- Cria a component controller e a tab bar
- Cria a PopMoviesViewModel 
- Implementa a ferramente "cascade operator"

2022-11-11 00:58 UTC, carlosbarceloss requested changes

2022-11-11 00:58 UTC, carlosbarceloss commented on PopMovies/PopMovies/Sources/Common/Enums/State.swift
> +enum State {
Do que se trata esse `State`? Não entendi, ficou abstrato demais. Qual é o escopo dele? 🤔

2022-11-11 00:58 UTC, carlosbarceloss commented on PopMovies/PopMovies/Sources/Views/ListGenres/Views/ListGenresViewController.swift
> +class ListGenresViewController: PMViewController {
`ListGenres` parece uma chamada para uma ação, o que você acha de alterar para `GenresListViewController`?

2022-11-11 00:58 UTC, carlosbarceloss commented on PopMovies/PopMovies/Sources/Views/FavoriteMovies/Views/FavoritesMovieViewController.swift
> +class FavoritesMoviesViewController: PMViewController {
Acredito que o correto seria apenas a palavra `movies` no plural
```suggestion
class FavoriteMoviesViewController: PMViewController {
```

2022-11-11 00:58 UTC, carlosbarceloss commented on PopMovies/PopMovies/Sources/Views/ListPopMovies/ViewModel/PopMoviesViewModel.swift
> +    var currentPage = 1
Essas propriedades vão ser acessadas externamente à `ViewModel`? 
Se não, creio que ambas poderiam ser `private`. É sempre bacana trabalhar o encapsulamento dos métodos e propriedades.

Outro detalhe é que seu `service` poderia ser uma constante, uma vez que você não vai alterar ele depois de implementado. Isso até mesmo te dá a segurança de que nenhum dos métodos vai sofrer qualquer tipo de alteração (isso porquê mesmo que as propriedades do `PMService` sejam `var`s, ou seja, mutáveis, pelo fato de a instância que você tem aqui ser uma constante, um `let`, não vai permitir alterar.)

Ex:
```swift
// Usando variáveis
var service: PMService

// Permite você fazer isso
service.myMethod = {} // ✅ - OK, é permitido fazer isso, desde que myMethod seja uma var também

// Já usando constantes
let service: PMService

// Não vai permitir a alteração
service.myMethod = {} // ❌ - não pode alterar propriedades de structs que são constantes
```

Aqui vai minha sugestão:
```suggestion
    private let service: PMService
    private var currentPage = 1
```

2022-11-11 00:58 UTC, carlosbarceloss commented on PopMovies/PopMovies/Sources/Views/ListPopMovies/Views/PopMoviesCell.swift
> +        let image = UIImage(systemName: "heart")!
o método `setImage` aceita uma imagem opcional, não precisa fazer esse force unwrap (é sempre bom evitar)
```suggestion
        let image = UIImage(systemName: "heart")
```

2022-11-11 00:58 UTC, carlosbarceloss commented on PopMovies/PopMovies/Sources/Views/ListPopMovies/Views/PopMoviesCell.swift
> +        stackView.edgesToSuperview(insets: .top(8) + .left(8) + .right(8) + .bottom(2), usingSafeArea: true)
```suggestion
        stackView.edgesToSuperview(insets: .top(8) + .bottom(2) + .horizontal(8), usingSafeArea: true)
```

2022-11-11 00:58 UTC, carlosbarceloss commented on PopMovies/PopMovies/Sources/Views/ListPopMovies/Views/PopMoviesView.swift
> +        configureConstraints()
não precisa chamar aqui, a própria `PMView` já chama esses métodos
```suggestion
```

2022-11-11 00:58 UTC, carlosbarceloss commented on PopMovies/PopMovies/Sources/Views/ListPopMovies/Views/PopMoviesView.swift
> +        configureConstraints()
Acredito que vc possa até remover esse `init` aqui

2022-11-11 00:58 UTC, carlosbarceloss commented on PopMovies/PopMovies/Sources/Views/ListPopMovies/Views/PopMoviesViewController.swift
> +    let viewModel = PopMoviesViewModel()
```suggestion
    private let viewModel = PopMoviesViewModel()
```

2022-11-11 00:58 UTC, carlosbarceloss commented on PopMovies/PopMovies/Sources/Views/ListPopMovies/Views/PopMoviesViewController.swift
> +    private lazy var collectionView = PopMoviesView()
aqui poderia chamar de `rootView`, por exemplo. `collectionView` parece mais o nome do componente kkkkk 🤔

2022-11-11 00:58 UTC, carlosbarceloss commented on PopMovies/PopMovies/Sources/Views/ListPopMovies/Views/PopMoviesViewController.swift
> +                    // mostrar errorview
👁️ 👄 👁️ 
não vai perder isso de vista hein

2022-11-21 15:39 UTC, angelavbalves commented on PopMovies/PopMovies/Sources/Views/ListGenres/Views/ListGenresViewController.swift
> +class ListGenresViewController: PMViewController {
Realizei essa mudança e as demais sugeridas em um novo PR #15

2022-12-05 12:27 UTC, merged