Feat/similar movies
angelavbalves/PopMovies pull request #7
Opened 2022-10-27 13:43 UTC by angelavbalves

### ℹ️ Descrição 
  Constrói a listagem de filmes similares na tela de detalhes

### 🎨 Mudanças
- Cria um componente de view separador para ser utilizado no layout
- Faz a requisição de filmes similares 
- Constrói o layout com uma collection view abaixo dos detalhes do filme
- Preenche a collection view com os filmes vindos da requisição

2022-12-03 00:00 UTC, carlosbarceloss commented on PopMovies/PopMovies/Sources/Views/MovieDetails/Views/MovieDetailsView.swift
> +        cell.layer.cornerRadius = 8.0
Por se tratar de estilização, acho que seria bacana isso aqui ficar dentro da própria célula, o que vc acha?

2022-12-03 00:01 UTC, carlosbarceloss requested changes

2022-12-03 00:01 UTC, carlosbarceloss commented on PopMovies/PopMovies/Sources/Views/MovieDetails/Views/MovieDetailsViewController.swift
> +    }
lembrar de sempre chamar o `super.viewDidLoad`
```suggestion
    override func viewDidLoad() {
        super.viewDidLoad()
        getSimilarMovies()
    }
```

2022-12-03 00:01 UTC, carlosbarceloss commented on PopMovies/PopMovies/Sources/Views/MovieDetails/Views/MovieDetailsViewController.swift
> +                    print("Error to get similar movies")
Depois tem que tratar esse erro 👀

2022-12-05 12:33 UTC, angelavbalves commented on PopMovies/PopMovies/Sources/Views/MovieDetails/Views/MovieDetailsViewController.swift
> +                    print("Error to get similar movies")
Sim, irei construir uma nova branch para tratar os erros

2022-12-05 12:37 UTC, angelavbalves commented on PopMovies/PopMovies/Sources/Views/MovieDetails/Views/MovieDetailsView.swift
> +        cell.layer.cornerRadius = 8.0
Colocarei isso dentro da célula em uma nova branch com as demais mudanças sugeridas

2022-12-05 13:06 UTC, merged